# spring
spring:
  # datasource
  datasource:
    # druid
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: admin
  # security
  security:
    user:
      password: 123456
# log
logging:
  level:
    com.lshaci.test: debug

